# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.


We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: **vectors** and **matrices**. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3] # list is an object

In [3]:
my_list

[1, 2, 3]

In [10]:
np.array(my_list) # cast a list to array

array([1, 2, 3])

In [11]:
p = np.array(my_list)

In [12]:
q = p.dot(p)
q

14

In [13]:
q = np.dot(p,p)
q

14

In [14]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In the above code, my_matrix is the list of three lists.

In [15]:
my_matrix = np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
your_matrix = [[1,2,4],[4,5,6],[7,8,9]]
your_matrix

[[1, 2, 4], [4, 5, 6], [7, 8, 9]]

In [17]:
your_matrix = np.array(your_matrix)
your_matrix

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.matmul(my_matrix,your_matrix)

array([[ 30,  36,  43],
       [ 66,  81, 100],
       [102, 126, 157]])

In [46]:
my_new_matrix = np.array([[1, 2],[3,4],[4,5]])
my_new_matrix

array([[1, 2],
       [3, 4],
       [4, 5]])

In [47]:
my_new_matrix.shape

(3, 2)

In [48]:
your_new_matrix = np.array([[1,2,3],[4,5,6]])
your_new_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
your_new_matrix.shape

(2, 3)

In [51]:
np.matmul(your_new_matrix,my_new_matrix)

array([[19, 25],
       [43, 58]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [30]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [80]:
np.random.rand(2)

array([0.43087675, 0.30971139])

In [81]:
np.random.rand(2)

array([0.0321989 , 0.50747405])

In [82]:
np.random.rand(5,5)

array([[0.03273155, 0.5730786 , 0.2342906 , 0.42505623, 0.16390871],
       [0.31007097, 0.966057  , 0.9491236 , 0.6897578 , 0.86670696],
       [0.26649739, 0.6335838 , 0.4821501 , 0.80650099, 0.16848574],
       [0.1333418 , 0.41321297, 0.66174374, 0.7617493 , 0.83790486],
       [0.59315928, 0.55143773, 0.21077977, 0.34467802, 0.10650061]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [37]:
np.random.rand(4) # the value is from zero to one (uniform distribution)

array([0.91278423, 0.56303871, 0.82849746, 0.13486727])

In [38]:
np.random.rand(2,2)

array([[0.12312823, 0.13169767],
       [0.60761358, 0.33661319]])

In [40]:
np.random.randn(5,5) # gaussian distribution/ normal distribution, centered around zero

array([[-1.31418146, -0.20128649,  0.06935567, -1.76488276, -1.04344538],
       [-1.84058218, -0.57424704,  1.50451211,  1.92286677,  0.53859132],
       [ 0.41381484, -0.90030792,  0.38027843,  1.29010104, -0.08640784],
       [ 0.60692399,  0.77802372,  0.30497745,  0.09170168,  0.57351286],
       [ 2.22543567,  1.12821085,  0.21387072, -0.10520519,  1.22448814]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [41]:
np.random.randint(1,100)

90

In [42]:
np.random.randint(1,100,10)

array([43, 45,  7,  4,  7, 51, 38, 31, 10, 25])

In [45]:
np.random.randint(1,100,(2,3))

array([[94, 54, 50],
       [42, 44, 60]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [46]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([20, 18, 23, 27, 48, 39, 24, 48, 40,  6])

## Reshape
Returns an array containing the same data with a new shape.

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr

array([20, 18, 23, 27, 48, 39, 24, 48, 40,  6])

In [51]:
ranarr.max()

48

In [52]:
ranarr.argmax()

4

In [53]:
ranarr.min()

6

In [54]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [55]:
# Vector
arr.shape

(25,)

In [56]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
arr.reshape(1,25).shape

(1, 25)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [60]:
arr.dtype

dtype('int32')